#endswith()

#1
string = "chinnari is good girl"
result = string.endswith("girl")
print(result)

#2

string = "python is my favourite language"
result = string.endswith("python")
print(result)

#3

string = "charminar one of most visiting place"
result = string.endswith("Place")
print(result)

#4

string = "10 is multiple of 2"
result = string.endswith("2")
print(result)

#5
string = "i loved fast food"
result = string.endswith(food)
print(result)