# join()
#1
string = "chinnari"
result = ".".join(string)
print(result)
#2
string = input("enter the string:")
join_string = ".".join(string)
print(join_string)
#3
tring = input("enter the string:")
string_a = string.split()
for item in string_a:
    result = ".".join(item)
    print(result)
#4
string = ("chinnari","sai","manoj")
join_string = "#".join(string)
print(join_string)
#5
string = ("chinnari","sai","anusha","praveen")
join_string = "#".join(string)
print(join_string)
    