#startswith()

string = "chinnari is a good girl"
result = string.startswith("chinnari")
print(result)

#2
string = "123 is a digits"
result = string.startswith("1")
print(result)

#3
string = "sai"
result = string.startswith("s")
print(result)

#4
string = "chinnari123"
result=string.startswith("chi")
print(result)

#5
string = "my mom is my bestfriend"
result = string.startswith("my")
print(result)